# ===============================================================================
# Copyright 2020 ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============================================================================


# ============= EOF =============================================
PIMAP = {
    "nmgrl": "NMGRL",
    "wcm": "McIntosh, M",
    "bill": "McIntosh, M",
    "bill gila": "McIntosh, M",
    "bill mcintosh": "McIntosh, M",
    "bill's gila": "McIntosh, M",
    "bill's gila redo": "McIntosh, M",
    "bill/lisa": "McIntosh, M",
    "mcintosh": "McIntosh, M",
    "mcintosh et al.": "McIntosh, M",
    "mcdowell": "McDowell, F",
    "henry": "Henry, C",
    "chris henry": "Henry, C",
    "c. henry": "Henry, C",
    "henry et al.": "Henry, C",
    "wilch": "Wilch, T",
    "thom": "Wilch, T",
    "tw": "Wilch, T",
    "thom wilch": "Wilch, T",
    "cather": "Cather, S",
    "chamberlin": "Chamberlin, R",
    "chamberlain": "Chamberlin, R",
    "r camberlain": "Chamberlin, R",
    "r chamberlain": "Chamberlin, R",
    "osborn": "Osborn, B",
    "bob osborn": "Osburn, B",
    "bob osburn": "Osburn, B",
    "osburn": "Osburn, B",
    "brian brister": "Brister, B",
    "brister": "Brister, B",
    "brian olmsted": "Olmsted, B",
    "b. olmsted": "Olmsted, B",
    "ariel": "Dickens, A",
    "axen": "Axen, G",
    "bauer": "Bauer, P",
    "p bauer": "Bauer, P",
    "c. ferguson": "Ferguson, C",
    "ferguson": "Ferguson, C",
    "ags-ferguson": "Ferguson, C",
    "chapin": "Chapin, C",
    "copeland": "Copeland, P",
    "crow": "Crow, R",
    "d love": "Love, D",
    "d. love": "Love, D",
    "d.love": "Love, D",
    "love": "Love, D",
    "lipman": "Lipman, P",
    "dale armstrong": "Armstrong, D",
    "dave gonzales": "Gonzales, D",
    "erin phillips": "Phillips, E",
    "giday": "Woldegabriel, G",
    "gidday": "Woldegabriel, G",
    "giday woldegabriel": "Woldegabriel, G",
    "giddaye": "Woldegabriel, G",
    "wolde gabriel": "Woldegabriel, G",
    "goff": "Goff, F",
    "harpel": "Harpel, C",
    "heizler": "Heizler, M",
    "heizler et al": "Heizler, M",
    "matt": "Heizler, M",
    "matt heizler": "Heizler, M",
    "mason-barton": "Mason-Barton, C",
    "j. gamble": "Gamble, J",
    "gamble": "Gamble, J",
    "gamble": "Gamble, J",
    "j. stroud": "Stroud, J",
    "joe stroud": "Stroud, J",
    "j. winick": "Winick, J",
    "jeff winick": "Winick, J",
    "jason rampe": "Rampe, J",
    "rampe": "Rampe, J",
    "jeff keith": "Keith, J",
    "jim faulds": "Faulds, J",
    "faulds": "Faulds, J",
    "joe moore": "Moore, J",
    "koning": "Koning, D",
    "zimmerer": "Zimmerer, M",
    "v lueth": "Lueth, V",
    "lueth": "Lueth, V",
    "umhoefer": "Umhoefer, P",
    "van laningham": "Laningham, V",
    "scott lynch": "Lynch, S",
    "lynch": "Lynch, S",
    "s janecke": "Janecke, S",
    "janecke": "Janecke, S",
    "s. nelson": "Nelson, S",
    "s. wilson": "Wilson, S",
    "ratte": "Ratte, J",
    "r benson": "Benson, R",
    "quade": "Quade, J",
    "p. kyle": "Kyle, P",
    "kyle": "Kyle, P",
    "esser": "Esser, R",
    "p link": "Link, P",
    "p wilson": "Wilson, P",
    "panter": "Panker, K",
    "greg mack": "Mack, G",
    "mack": "Mack, G",
    "morgan": "Morgan, L",
    "lisa morgan": "Morgan, L",
    "karlstrom": "Karlstrom, K",
    "julie calkins": "Calkins, J",
    "carol hill": "Hill, C",
    "ed sable": "Sable, E",
    "petronis": "Petronis, M",
    "mike petronis": "Petronis, M",
    "miggins": "Miggins, D",
    "mclemore": "McLemore, V",
    "mcmillan": "McMillan, N",
    "f gray": "Gray, F",
    "f. pazzaglia": "Pazzaglia, F",
    "mike wells": "Wells, M",
    "peter pollard": "Pollard, P",
    "iriondo": "Iriondo, A",
    "v. ispolatov": "Ispolatov, V",
    "ispolatov": "Ispolatov, V",
    "vera p.": "Vera, P",
    "spell": "Spell, T",
    "yancey": "Yancey, A",
    "biek": "Biek, B",
    "ross": "Ross, J",
    "amato": "Amato, J",
    "b north": "North, B",
    "fred phillips": "Phillips, F",
    "gary smith": "Smith, G",
    "geismann": "Geissman, J",
    "geissman": "Geissman, J",
    "peters": "Peters, L",
    "polyak": "Polyak, V",
    "r. appelt": "Appelt, R",
    "samuels": "Samuels, K",
    "sanders": "Sanders, R",
    "smellie": "Smellie, J",
    "constenius": "Constenius, K",
    "g. smith": "Smith, G",
    "g.smith": "Smith, G",
    "fassett": "Fassett, J",
    "d. larsen": "Larsen, D",
    "d. powers": "Powers, D",
    "chesner": "Chesner, C",
    "blair": "Blair, T",
    "blamey": "Blamey, N",
    "chavez": "Chavez, B",
    "gonzales": "Gonzales, D",
    "keller": "Keller, G",
    "kelley": "Kelley, S",
    "kelson": "Kelson, A",
    "miller": "Miller, C",
    "nelson": "Nelson, S",
    "phillips": "Phillips, E",
    "potter": "Potter, L",
    "price": "Price, J",
    "smith": "Smith, A",
    "stern": "Stern, B",
    "templeton": "Templeton, J",
    "victor polyak": "Polyak, V",
    "walter": "Walter, B",
    "wells": "Wells, M",
    "timmons": "Timmons, M",
    "siddoway": "Siddoway, C",
}

MATMAP = {
    "amp": "Amphibole",
    "amph.": "Amphibole",
    "amph": "Amphibole",
    "adularia": "Adularia",
    "audularia": "Adularia",
    "audular": "Adularia",
    "aud": "Adularia",
    "adul": "Adularia",
    "adular": "Adularia",
    "adu": "Adularia",
    "adl": "Adularia",
    "adul.": "Adularia",
    "alun": "Alunite",
    "alunite": "Alunite",
    "anorthoclase": "Anorthoclase",
    "anorth": "Anorthoclase",
    "anorth.": "Anorthoclase",
    "barite": "Barite",
    "bi": "Biotite",
    "bio": "Biotite",
    "biot": "Biotite",
    "biotite": "Biotite",
    "biot.": "Biotite",
    "biote": "Biotite",
    "feldspar": "Feldspar",
    "fspar": "Feldspar",
    "feld": "Feldspar",
    "gm": "Groundmass",
    "g-mass": "Groundmass",
    "hbl": "Hornblende",
    "hlb": "Hornblende",
    "hornblende": "Hornblende",
    "illite": "Illite",
    "jarosite": "Jarosite",
    "jaro": "Jarosite",
    "jaro.": "Jarosite",
    "ksp": "K-Feldspar",
    "k-spar": "K-Feldspar",
    "kfeldspar": "K-Feldspar",
    "kspar": "K-Feldspar",
    "leucite": "Leucite",
    "musc": "Muscovite",
    "musc.": "Muscovite",
    "mus": "Muscovite",
    "ms": "Muscovite",
    "mica": "Mica",
    "obsid": "Obsidian",
    "obsidian": "Obsidian",
    "orthoclase": "Orthoclase",
    "ortho.": "Orthoclase",
    "phlogopite": "Phlogopite",
    "phlog.": "Phlogopite",
    "plag": "Plagioclase",
    "plag.": "Plagioclase",
    "plagioclase": "Plagioclase",
    "qtz": "Quartz",
    "quartz": "Quartz",
    "quarz": "Quartz",
    "san": "Sanidine",
    "sanidine": "Sanidine",
    "sericite": "Sericite",
    "smectite": "Smectite",
    "tourmaline": "Tourmaline",
    "tour": "Tourmaline",
    "wr": "WholeRock",
    "wh. rock": "WholeRock",
    "whole rock": "WholeRock",
}
