def main():
    info('Prepare for Air Shot')
    close(description='Felix Inlet')
    open(description='Felix Ion Pump')
    close(description='Microbone to Minibone')
    close(description='Quad Inlet')
    open(description='Bone to Turbo')
    open(description='Bone to Minibone')
    open(description='Minibone to Bone')
    open(description='Bone to Getter GP-50')
    close(description='Bone to CO2 Laser')
    close(description='Bone to Diode Laser')