"""add measuredpositiontable

Revision ID: 146580790cd
Revises: 2902af6c9ef9
Create Date: 2015-09-25 11:25:11.921242

"""

# revision identifiers, used by Alembic.
revision = '146580790cd'
down_revision = '2902af6c9ef9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LoadPositionTbl',
                    sa.Column('idloadpositionTbl', sa.Integer(), nullable=False),
                    sa.Column('identifier', sa.String(length=80), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=True),
                    sa.Column('loadName', sa.String(length=45), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.Column('note', sa.BLOB(), nullable=True),
                    sa.ForeignKeyConstraint(['identifier'], ['IrradiationPositionTbl.identifier'], ),
                    sa.ForeignKeyConstraint(['loadName'], ['LoadTbl.name'], ),
                    sa.PrimaryKeyConstraint('idloadpositionTbl')
                    )
    op.create_table('MeasuredPositionTbl',
                    sa.Column('idmeasuredpositionTbl', sa.Integer(), nullable=False),
                    sa.Column('position', sa.Integer(), nullable=True),
                    sa.Column('x', sa.Float(), nullable=True),
                    sa.Column('y', sa.Float(), nullable=True),
                    sa.Column('z', sa.Float(), nullable=True),
                    sa.Column('is_degas', sa.Boolean(), nullable=True),
                    sa.Column('analysisID', sa.Integer(), nullable=True),
                    sa.Column('loadName', sa.String(length=45), nullable=True),
                    sa.ForeignKeyConstraint(['analysisID'], ['AnalysisTbl.idanalysisTbl'], ),
                    sa.ForeignKeyConstraint(['loadName'], ['LoadTbl.name'], ),
                    sa.PrimaryKeyConstraint('idmeasuredpositionTbl')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MeasuredPositionTbl')
    op.drop_table('LoadPositionTbl')
    ### end Alembic commands ###
